import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import BasePage from "@/components/BasePage/BasePage";
import "./globals.css";
import "@/stylesheets/theme.scss";

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Benrogo",
    default: "Home | Benrogo"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceCodePro.variable}>
        <AppRouterCacheProvider>
          <BasePage>
            {children}
          </BasePage>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
